# Generated by Django 5.1 on 2024-08-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_conversation_name_alter_deal_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='dealTime',
        ),
    ]
