# Generated by Django 5.1 on 2024-08-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_deal_dealtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='money',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='deal',
            name='profit',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='place',
            field=models.CharField(max_length=100),
        ),
    ]
