 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: personal-k8s-app-deployment
 spec:
   replicas: 2
   selector:
     matchLabels:
       app: backend
   template:
     metadata:
       labels:
         app: backend
     spec:
       containers:
       - name: backend
         image: testuser000111/backend
         ports:
         - containerPort: 5000