services:

  frontend:
    image: frontend
    env_file: 
      - .env
    ports: 
      - "5173:5173"
    networks:
      - frontend-management
      - management-prometheus
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules

  backend:
    image: backend
    ports:
      - "8000:8000"
    networks:
      - backend-management
      - management-prometheus
    depends_on:
      - db

  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - management-database

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - management-prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - management-grafana

volumes:
  app-db-data:
  grafana-data:

networks:
  frontend-management:   
    driver: bridge
  backend-management:   
    driver: bridge
  management-database:   
    driver: bridge
  management-prometheus:   
    driver: bridge
  management-grafana:   
    driver: bridge
