services:
  frontend:
    image: frontend
    container_name: typescript-vite
    ports: 
      - "5173:5173"
    networks:
      - management-network
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules

  backend:
    image: backend
    container_name: django
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - management-network
    depends_on:
      - database

  database: #this line have to be the same like HOST in backend to connect database
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - management-network

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgres://postgres:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_NAME}?sslmode=disable
    ports:
      - "9187:9187"
    networks:
      - management-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - management-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - management-network

  loki:
    container_name: loki
    image: grafana/loki:2.3.0
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml  # Make sure loki-config.yaml is at the correct path
      - loki-data:/loki
    command:
      -config.file=/etc/loki/loki-config.yaml
    networks:
      - management-network

  promtail:
    container_name: promtail
    image: grafana/promtail:2.3.0
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml  # Make sure promtail-config.yaml is at the correct path
    command:
      -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
    networks:
      - management-network

volumes:
  db-data:
  grafana-data:
  loki-data:
  prometheus_data:

networks:
  management-network:
    driver: bridge
