global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1m # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
   alertmanagers:
     - static_configs:
       - targets: 
        - alertmanager:9093

   

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'database'
    static_configs:
      - targets: ['postgres_exporter:9187']