name: Django CI
on:
  push:
    branches: ["main"]

jobs:
  test-django-app:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: testpostgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12.4"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install coverage

      - name: Run Django Tests
        env:
          DJANGO_SETTINGS_MODULE: app.settings
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/testpostgres
        run: |
          cd backend
          python -m coverage run manage.py test
          python -m coverage report